### ISSUE TITLE
Polling and calc_next_run()

### ISSUE THREAD

**Issue by Antexa** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#46] opened 2022-06-02 18:46 UTC
Do you think it is possible to remove or lower the sleep_seconds of 30 seconds in the calc_next_run function ? 

This lead sometime into a 2 min wait time even if a every minute schedule is configured in the crontab.

**Comment by Dielee** [comment] 2022-06-16 15:40
Yeah, this was done to prevent blocking from tgtg. Maybe we can move this setting into the settings file. But there should be an min value of x seconds.. Maybe not lower than 10 seconds. @MaxWinterstein ?

**Comment by TerrorSource** [comment] 2022-06-16 18:01
I prefer a timer which we can set ourselfs. Got a tgtg shop with is very populair so i'm too late with a minute interval

(thats also the reason i'm using an ON- and OFF-timer for the add on so it doesnt run 24/7 but only at selected times)

**Comment by Dielee** [comment] 2022-06-16 18:37
Polling the tgtg API more than once a minute often results in a IP ban.. this is the reason why we build this feature with Cron schedule and a randomized sleep time.

**Comment by TerrorSource** [comment] 2022-06-16 18:51
> Polling the tgtg API more than once a minute often results in a IP ban.. this is the reason why we build this feature with Cron schedule and a randomized sleep time.

does not result in an IP-ban if you do it only for like 15-20minutes a day. for example, if you 4 request per minute for 15 minutes it still only 60 requests per day. if you continue to keep polling 1 request per minute the whole day there are 1440 requests.

**Comment by Dielee** [comment] 2022-06-16 18:56
@MaxWinterstein what do you think about it ? I don't think this is a good idea, as polling seems to be not counted over the whole day. They block if you are poll to often in a few minutes and the polling intervall stays the same.

**Comment by MaxWinterstein** [comment] 2022-06-18 19:54
Well, as far as I know, there is no clearly documented way to get banned, or not. Therefore I am a big fan of beeing careful.

While creating `v2.2.2` I saw it myself:
```
2022-06-18 21:34:54 [INFO] Next run at 2022-06-18 21:42:58 
```

Waiting around 8 minutes is a little bit too much imho.

So maybe we want to redo the sleeping a little bit, and provide some flags to skip sleeping if an experienced user wants to.

**Comment by Dielee** [comment] 2022-06-19 07:48
Whats going on there ? 8 Minutes, never seen this... Check your config maybe ? 
I will add the option to skip random sleep in the upcomming week.

**Comment by HanBarn** [comment] 2022-06-19 10:10
I just started using this TGTG integration yesterday.
I have noticed there were some very recent changes and started with version 2.2.0 while the next was already in progress.
This morning I have installed 2.2.2 which seems to run fine although there are no TGTG boxes available right now because it’s Sunday.
The logging shows a strange timing probably because of the safe polling time you used.
The polling is not exactly each 10 minutes according the cron entry in the configuration.

The best solution (I think) is to use a low interval during the evening/night if the are no boxes available and to use a higher frequency on request during the daytime if you expect new boxes from the favorite shops.


2022-06-19 11:35:55 [INFO] Next run at 2022-06-19 11:43:25
2022-06-19 11:43:25 [INFO] Next run at 2022-06-19 11:56:23
2022-06-19 11:56:24 [INFO] Next run at 2022-06-19 12:02:30
2022-06-19 12:02:30 [INFO] Next run at 2022-06-19 12:17:15

**Comment by Dielee** [comment] 2022-06-19 10:27
Yeah polling is randomized as tgtg is very sensitive with API calls. If the polling would run all 10 minutes, your IP could be banned. In the next version you will be able to deactivate the random polling.

**Comment by HanBarn** [comment] 2022-06-19 10:43
> 

Thanks for your fast reply.
Yes, I agree that very frequent polling would cause an overload to the TGTG API.
But most of the time during the day very frequent polling is not needed. 
A more dynamic schedule would be nice.
So during the evening/night for example once every half hour but (preferably on request) each minute if you need a box from shop X which usually start to publish boxes at around 15:00 or so.

**Comment by Dielee** [comment] 2022-06-19 11:17
Maybe we would listen to predefined mqtt topic to realize the "on request" feature ? 

If there was send something we change the polling intervall to x seconds.

**Comment by Dielee** [comment] 2022-06-20 09:39
Yeah, improvement is cooking. Maybe this will be merged today. 
Feel free to clone and build the test branch localy: https://github.com/Dielee/toogoodtogo-ha-mqtt-bridge/tree/add-intense-mode-feature

Feedback is welcome!

**Comment by Paul-Vdp** [comment] 2022-06-20 09:52
Not clear on when the 'intense fetch' would kick in, or how/what is supposed to activate it ?

**Comment by MaxWinterstein** [comment] 2022-06-20 11:42
I am a fan of “intense mode” - even it might need some more details on how to use it on the readme file. 

The idea behind it is pretty simple, and should solve the case of @Paul-Vdp.  
Just set the default cron to every hour, and use some automation to toggle the ‘intense mode’ whenever you need it. This will fetch for e.g. the next 5 minutes at an Intervall of 30 seconds, or lower.

**Comment by Dielee** [comment] 2022-06-20 11:54
Thanks @MaxWinterstein for the detailed description!

**Comment by MaxWinterstein** [comment] 2022-06-21 08:47
`intense_mode` has been merged, just need to create a matching home assistant Add-On adjustment and release. Give me some time ;)

**Comment by MaxWinterstein** [comment] 2022-06-26 10:42
`intense_mode` is now available <3

--- 
_note for myself / dieele:_ found another nice one: 
```
2022-06-26 12:41:26 [INFO] Next run at 2022-06-26 12:55:30
```
at
10 minutes fetch interval

**Comment by HanBarn** [comment] 2022-06-26 12:52
Just updated to 2.3.0.
I have noticed the update this afternoon.
The new intense mode switch is available now.
But nothing in the documentation about the use of it.
It is clear you can set the interval and period, but do you have to set intense mode to the status ON or OFF?
The current status of switch.intense_fetch is unknown not ON or OFF according the Home Assistant development tools.
It is of course possible to change the status manually of by automation to the desired status.

**Comment by MaxWinterstein** [comment] 2022-06-26 17:12
Only used it from the GUI before:
![image](https://user-images.githubusercontent.com/5927148/175825400-4dc523eb-debc-4551-b785-87daf720e6d4.png)


Awesome to see that it works!  
Yeah, maybe we should add some screenshots to the documentation, or how to use it in automation.

`ON / OFF` vs `on / off` seems tricky. We sent uppercase states, the developer tools show lower case.

![image](https://user-images.githubusercontent.com/5927148/175825635-aeeb02bc-bf5e-4001-aa7f-e280e3df35c9.png)

But, as far as I see, this is common usage on that part.

**Comment by MaxWinterstein** [comment] 2022-07-03 19:05
We will keep this issue open until we did some rework on the polling schedule. 

To be honest, not on my priority list, as it works and initial polling can now be enforced via intense fetch ✌️

**Comment by crydante** [comment] 2022-11-12 21:35
Hello,

With this cron : 

polling_schedule: "*/10 7-20 * * *"

at the end of the day, the next run hour is wrong : 

2022-11-12 20:54:44 [DEBUG] Loop run finished
2022-11-12 20:54:44 [INFO] Next run at 2022-11-13 14:16:08

**Comment by MaxWinterstein** [comment] 2023-01-15 22:46
@crydante wow, in fact, that is bad. 

Error is caused by this function:
https://github.com/MaxWinterstein/toogoodtogo-ha-mqtt-bridge/blob/a8da85429bf826ba93f2931b4a788f486e754dff/toogoodtogo_ha_mqtt_bridge/main.py#L370-L375

Which takes the sleep time as a base to randomize things. Will do some rework on this.

**Comment by MaxWinterstein** [comment] 2023-01-27 15:24
This has been reworked and should be fine.

**Closed by MaxWinterstein** 2023-01-27 15:24 UTC
